# torchtitan Config.toml
# NOTE: this toml config is a preset for 16 H100 GPUs.
# TODO: find out how to set FSDP full-shard

[job]
dump_folder = "${MODEL_PATH}/torchtitan-outputs"
description = "Llama 3 70B training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = true
save_tb_folder = "${MODEL_PATH}/torchtitan-tb"

[model]
name = "llama3"
flavor = "70B"
norm_type = "rmsnorm"                                        # [layernorm, np_layernorm, rmsnorm, fused_rmsnorm]
tokenizer_path = "${MODEL_PATH}/${HF_MODEL}/tokenizer.model"

[optimizer]
name = "AdamW"
lr = 1.5e-4

[training]
batch_size = 1
seq_len = 8192
warmup_steps = 200           # lr scheduler warm up, normally 20% of the train steps
max_norm = 1.0               # grad norm clipping
steps = 1000
data_parallel_degree = -1
tensor_parallel_degree = 8   # 8-way TP
pipeline_parallel_degree = 1
fp8_linear = ""
compile = false
dataset = "c4"
reshard_after_forward = true

[checkpoint]
enable_checkpoint = true
folder = "${MODEL_PATH}/torchtitan-checkpoint"
interval_type = "steps"
interval = 500
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled"                        # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'full'
