name: training-job-deployer
version: 1.1.0
description: |
  Deploy and manage distributed training jobs on EKS using torchrun.
  Supports both kubectl and HyperPod CLI with automatic torchrun configuration,
  failure detection, log streaming, and intelligent retry with fixes.
  
  Key Features:
  - Automatic torchrun configuration for multi-node distributed training
  - PyTorchJob-compatible manifest generation
  - Support for FSDP, DDP, and other distributed strategies
  - Built-in checkpoint volume mounting
  - HuggingFace integration with token support

triggers:
  - type: command
    pattern: "/deploy-training-job"
    description: "Deploy training job to EKS with torchrun"

parameters:
  - name: job_name
    type: string
    default: "fsdp-training"
    description: "Job name"
  
  - name: image_uri
    type: string
    default: ""
    description: "Docker image URI (auto-detect if empty)"
  
  - name: instance_type
    type: string
    default: "ml.g5.8xlarge"
    description: "Instance type"
  
  - name: num_nodes
    type: integer
    default: 4
    description: "Number of nodes for distributed training"
  
  - name: gpu_per_node
    type: integer
    default: 1
    description: "Number of GPUs per node"
  
  - name: cluster_name
    type: string
    default: ""
    description: "EKS cluster name"
  
  - name: torchrun_path
    type: string
    default: "/opt/conda/bin/torchrun"
    description: "Path to torchrun executable in container"
  
  - name: use_hyperpod_cli
    type: string
    default: "auto"
    description: "Use HyperPod CLI: auto, true, or false"
  
  - name: monitor
    type: boolean
    default: true
    description: "Monitor job after deployment"
  
  - name: auto_retry
    type: boolean
    default: true
    description: "Auto-retry on known failures"
  
  - name: save_config
    type: boolean
    default: true
    description: "Save config to ConfigMap"
  
  - name: hf_token
    type: string
    default: ""
    description: "HuggingFace token for gated models"
  
  - name: sns_topic
    type: string
    default: ""
    description: "SNS topic ARN for notifications"

outputs:
  - name: job_status
    type: string
    description: "Job status (Running, Succeeded, Failed)"
  
  - name: master_pod
    type: string
    description: "Master pod name (worker-0)"
  
  - name: fixes_applied
    type: array
    description: "List of fixes applied during deployment"
  
  - name: torchrun_config
    type: object
    description: "Torchrun configuration used for distributed training"

dependencies:
  - aws-cli
  - kubectl
  - docker
  - python3
  - pyyaml

examples:
  - command: "/deploy-training-job"
    description: "Deploy with default settings (4 nodes, 1 GPU each)"
  
  - command: "/deploy-training-job --job-name llama-3b-training --num-nodes 8 --gpu-per-node 2"
    description: "Deploy Llama 3B training on 8 nodes with 2 GPUs each"
  
  - command: "/deploy-training-job --cluster-name my-cluster --image-uri 123456789.dkr.ecr.us-west-2.amazonaws.com/my-training:latest"
    description: "Deploy with custom cluster and image"
  
  - command: "/deploy-training-job --hf-token $HF_TOKEN --model-type meta-llama/Llama-3.2-1B"
    description: "Deploy with HuggingFace token for gated models"
  
  - command: "/deploy-training-job --monitor --auto_retry"
    description: "Deploy with real-time monitoring and auto-retry on failures"

author: opencode
license: MIT
