---
- name: "Install python and gcc"
  ansible.builtin.yum:
    name:
      - python3.7-venv
      - gcc-c++
    state: present
- name: "Install Neuron Driver"
  ansible.builtin.shell: |
    # Install Python venv 
    sudo yum install -y python3.7-venv gcc-c++ 

    # Create Python venv
    python3.7 -m venv aws_neuron_venv_pytorch 

    # Activate Python venv 
    source aws_neuron_venv_pytorch/bin/activate 
    python -m pip install -U pip 

    # Install Jupyter notebook kernel
    pip install ipykernel 
    python3.7 -m ipykernel install --user --name aws_neuron_venv_pytorch --display-name "Python (torch-neuronx)"
    pip install jupyter notebook
    pip install environment_kernels

    # Set pip repository pointing to the Neuron repository 
    python -m pip config set global.extra-index-url https://pip.repos.neuron.amazonaws.com

    # Install wget, awscli 
    python -m pip install wget 
    python -m pip install awscli 

    # Install Neuron Compiler and Framework
    python -m pip install neuronx-cc==2.* torch-neuronx torchvision
