---
- name: "Enable Python38"
  ansible.builtin.shell: |
    amazon-linux-extras enable python3.8
- name: "Install python and gcc"
  ansible.builtin.yum:
    name:
      - gcc-c++
      - python38
      - python38-devel
    state: present

- name: "Install PyTorch Neuron"
  ansible.builtin.shell: |
    # Create Python venv
    python3.8 -m venv aws_neuron_venv_pytorch 

    # Activate Python venv 
    source aws_neuron_venv_pytorch/bin/activate 
    python3.8 -m pip install -U pip 

    # Install Jupyter notebook kernel
    pip install ipykernel 
    python3.8 -m ipykernel install --user --name aws_neuron_venv_pytorch --display-name "Python (torch-neuronx)"
    pip install jupyter notebook
    pip install environment_kernels

    # Set pip repository pointing to the Neuron repository 
    python3.8 -m pip config set global.extra-index-url https://pip.repos.neuron.amazonaws.com

    # Install wget, awscli 
    python3.8 -m pip install wget 
    python3.8 -m pip install awscli 

    # Install Neuron Compiler and Framework
    python3.8 -m pip install neuronx-cc==2.* torch-neuronx torchvision
  args:
    chdir: /home/ec2-user

- name: "Clone neuronx-nemo-megatron"
  ansible.builtin.git:
    repo: https://github.com/aws-neuron/neuronx-nemo-megatron.git
    dest: /home/ec2-user/neuronx-nemo-megatron

- name: "Install neuronx-nemo-megatron"
  ansible.builtin.shell: |
    # Activate Python venv 
    source aws_neuron_venv_pytorch/bin/activate 
    cd neuronx-nemo-megatron
    pip install wheel
    ./build.sh
    pip3 install ./build/*.whl
    pip3 install -r requirements.txt torch==1.13.1 protobuf==3.20.3
  args:
    chdir: /home/ec2-user

- name: "Build the Megatron helper module"
  ansible.builtin.shell: |
    # Activate Python venv 
    source aws_neuron_venv_pytorch/bin/activate 
    python -c "from nemo.collections.nlp.data.language_modeling.megatron.dataset_utils import compile_helper; compile_helper()"
  args:
    chdir: /home/ec2-user
