apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fsx-sc
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: FSX_Filesystem_ID # from AWS FSx console: File system ID
    volumeAttributes:
      dnsname: FSX DNS Name # from AWS FSx console: DNS name
      mountname: Mount Name # from AWS FSx console: Mount name
