{
 "title": "AWS FSx for Lustre",
 "description": "Visualize AWS FSx metrics",
 "tags": [
  "hyperpod",
  "aws",
  "fsx",
  "aws-sagemaker-hyperpod"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "filesystemid",
    "label": "FileSystemId",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "FreeStorageCapacity/DeduplicationSavedStorage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FreeStorageCapacity",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DeduplicationSavedStorage",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Additional metrics and logs", "type": "dashlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "CPUUtilization/MemoryUtilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "StorageCapacityUtilization/FileServerDiskIopsUtilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "StorageCapacityUtilization",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FileServerDiskIopsUtilization",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "NetworkThroughputUtilization/FileServerDiskThroughputUtilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkThroughputUtilization",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FileServerDiskThroughputUtilization",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "ClientConnections/MetadataOperations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ClientConnections",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "MetadataOperations",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "FileServerDiskIopsBalance/FileServerDiskThroughputBalance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FileServerDiskIopsBalance",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FileServerDiskThroughputBalance",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "DiskThroughputUtilization/DiskIopsUtilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DiskThroughputUtilization",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DiskIopsUtilization",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "DiskReadBytes/DiskWriteBytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DiskReadBytes",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DiskWriteBytes",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "DiskReadOperations/DiskWriteOperations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DiskReadOperations",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DiskWriteOperations",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "DataReadBytes/DataWriteBytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DataReadBytes",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DataWriteBytes",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "DataReadOperations/DataWriteOperations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DataReadOperations",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "FileSystemId": "$filesystemid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DataWriteOperations",
     "namespace": "AWS/FSx",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 78 },
   "options": {
    "content": "<a target=\"_blank\" href=\"http://www.monitoringartist.com\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/fsx/latest/WindowsGuide/fsx-windows-metrics.html\">AWS CloudWatch FSx documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/x\">Installed from Grafana.com dashboards</a>"
   },
   "targets": [
    {}
   ]
  }
 ]
}