---
- name: "Add nvidia-docker repo"
  ansible.builtin.shell: yum-config-manager --add-repo https://nvidia.github.io/nvidia-docker/amzn2/nvidia-docker.repo
  args:
    creates: /etc/yum.repos.d/nvidia-docker.repo

- name: "Intall Nvidia docker packages"
  yum:
    name:
      - nvidia-container-toolkit
      - nvidia-docker2
    state: present
    update_cache: yes

- name: "(Re)start docker"
  ansible.builtin.systemd:
    name: docker.service
    state: restarted

- name: yum clean metadata
  ansible.builtin.command:
    cmd: yum clean metadata
