name: docker-image-tester
version: 1.0.0
description: |
  Comprehensive testing framework for Docker images with automatic 
  fix recommendations. Tests imports, model instantiation, forward 
  passes, dataset loading, and checkpoint operations.

triggers:
  - type: command
    pattern: "/test-docker-image"
    description: "Test a Docker image comprehensively"
  - type: post_build
    pattern: "docker-image-builder"
    description: "Auto-trigger after successful build"

parameters:
  - name: image
    type: string
    default: ""
    description: "Image name to test (uses latest built if empty)"
  
  - name: level
    type: string
    default: "standard"
    description: "Test level: quick, standard, or full"
  
  - name: generate_report
    type: boolean
    default: true
    description: "Generate test report"
  
  - name: report_format
    type: string
    default: "json"
    description: "Report format: json, html, or both"
  
  - name: output_dir
    type: string
    default: "./test-reports"
    description: "Directory to save test reports"
  
  - name: verbose
    type: boolean
    default: true
    description: "Show detailed test output"
  
  - name: use_sudo
    type: boolean
    default: false
    description: "Use sudo for Docker commands"

outputs:
  - name: test_results
    type: object
    description: "Complete test results"
  
  - name: passed
    type: integer
    description: "Number of tests passed"
  
  - name: failed
    type: integer
    description: "Number of tests failed"
  
  - name: report_path
    type: string
    description: "Path to generated report"
  
  - name: fix_recommendations
    type: array
    description: "List of recommended fixes"
  
  - name: success
    type: boolean
    description: "Whether all tests passed"

dependencies:
  - docker
  - python3

examples:
  - command: "/test-docker-image"
    description: "Test with default settings"
  
  - command: "/test-docker-image --image myapp:latest --level full"
    description: "Run full test suite on specific image"
  
  - command: "/test-docker-image --level quick --report_format html"
    description: "Quick test with HTML report"

author: opencode
license: MIT
