apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fsx-sc
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-0f801be34fa705d1b # from AWS FSx console: File system ID
    volumeAttributes:
      dnsname: fs-0f801be34fa705d1b.fsx.us-west-2.amazonaws.com # from AWS FSx console: DNS name
      mountname: 4wz35bev # from AWS FSx console: Mount name

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fsx-sc
  resources:
    requests:
      storage: 1200Gi