---
- name: "Install git"
  ansible.builtin.yum:
    name:
      - git
    state: present
- name: "Install Neuron Driver"
  block:
    - name: "Configure Linux for Neuron repository update"
      ansible.builtin.blockinfile:
        path: /etc/yum.repos.d/neuron.repo
        create: yes
        block: |
          [neuron]
          name=Neuron YUM Repository
          baseurl=https://yum.repos.neuron.amazonaws.com
          enabled=1
          metadata_expire=0
    - name: "import rpm"
      ansible.builtin.shell: |
        rpm --import https://yum.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB
    - name: "Update yum"
      ansible.builtin.yum:
        name: "*"
        state: latest
    - name: "Install OS headers"
      ansible.builtin.shell:
        cmd: yum install -y kernel-devel-$(uname -r) kernel-headers-$(uname -r)
    - name: "Install Neuron Driver, Runtime, and Tools"
      ansible.builtin.yum:
        name:
          - aws-neuronx-dkms-2.*
          - aws-neuronx-collectives-2.*
          - aws-neuronx-runtime-lib-2.*
          - aws-neuronx-tools-2.*
    - name: "Set PATH"
      ansible.builtin.blockinfile:
        path: /etc/profile.d/neuron.sh
        create: yes
        block: |
          export PATH=$PATH:/opt/aws/neuron/bin
