AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AWS CodeBuild infrastructure for PyTorch FSDP Docker image building.
  Creates CodeBuild project, ECR repository, S3 bucket, IAM role, and CloudWatch logs.

Parameters:
  ProjectName:
    Type: String
    Default: pytorch-fsdp
    Description: Name of the CodeBuild project
    MinLength: 1
    MaxLength: 255
    AllowedPattern: '^[a-zA-Z0-9-_]+$'
    ConstraintDescription: Must contain only alphanumeric characters, hyphens, and underscores

  RepositoryName:
    Type: String
    Default: fsdp
    Description: Name of the ECR repository
    MinLength: 2
    MaxLength: 256

  GitHubRepository:
    Type: String
    Default: ''
    Description: GitHub repository URL (e.g., https://github.com/user/repo)

  GitHubBranch:
    Type: String
    Default: main
    Description: GitHub branch to build

  Region:
    Type: String
    Default: us-west-2
    Description: AWS Region
    AllowedValues:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - eu-west-1
      - eu-west-2
      - eu-central-1
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-1

  BuildTimeout:
    Type: Number
    Default: 60
    Description: Build timeout in minutes
    MinValue: 5
    MaxValue: 480

  ComputeType:
    Type: String
    Default: BUILD_GENERAL1_MEDIUM
    Description: CodeBuild compute type
    AllowedValues:
      - BUILD_GENERAL1_SMALL
      - BUILD_GENERAL1_MEDIUM
      - BUILD_GENERAL1_LARGE
      - BUILD_GENERAL1_2XLARGE

  EnableWebhook:
    Type: String
    Default: 'true'
    Description: Enable GitHub webhook trigger
    AllowedValues:
      - 'true'
      - 'false'

  EnableScheduledBuilds:
    Type: String
    Default: 'true'
    Description: Enable nightly scheduled builds
    AllowedValues:
      - 'true'
      - 'false'

  ScheduleExpression:
    Type: String
    Default: 'cron(0 2 * * ? *)'
    Description: CloudWatch Events schedule expression (UTC)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Project Configuration
        Parameters:
          - ProjectName
          - RepositoryName
      - Label:
          default: Source Configuration
        Parameters:
          - GitHubRepository
          - GitHubBranch
      - Label:
          default: Build Configuration
        Parameters:
          - Region
          - BuildTimeout
          - ComputeType
      - Label:
          default: Trigger Configuration
        Parameters:
          - EnableWebhook
          - EnableScheduledBuilds
          - ScheduleExpression

Resources:
  # IAM Role for CodeBuild
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-codebuild-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: !Sub '${ProjectName}-codebuild-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # ECR Permissions
              - Sid: ECRAccess
                Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
                  - ecr:CreateRepository
                  - ecr:DescribeRepositories
                  - ecr:DescribeImages
                Resource: '*'
              
              # S3 Permissions
              - Sid: S3Access
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetObjectVersion
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${ArtifactBucket}'
                  - !Sub 'arn:aws:s3:::${ArtifactBucket}/*'
              
              # Secrets Manager (for GitHub token if needed)
              - Sid: SecretsManagerAccess
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub 'arn:aws:secretsmanager:${Region}:${AWS::AccountId}:secret:${ProjectName}/*'
              
              # CloudWatch Events (for scheduled builds)
              - Sid: CloudWatchEventsAccess
                Effect: Allow
                Action:
                  - events:PutRule
                  - events:PutTargets
                  - events:DescribeRule
                Resource: '*'

  # S3 Bucket for Build Artifacts
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-build-artifacts-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
          - Id: DeleteOldArtifacts
            Status: Enabled
            ExpirationInDays: 90

  # ECR Repository
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      EncryptionConfiguration:
        EncryptionType: AES256
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 30 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 30
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

  # CloudWatch Log Group
  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/codebuild/${ProjectName}'
      RetentionInDays: 30

  # CodeBuild Project
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      Description: Build, test, and push PyTorch FSDP Docker images
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: S3
        Location: !Ref ArtifactBucket
        Path: build-output
        NamespaceType: BUILD_ID
        Name: artifacts
        Packaging: NONE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: !Ref ComputeType
        Image: aws/codebuild/standard:7.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref Region
          - Name: ECR_REPOSITORY
            Value: !Ref RepositoryName
          - Name: PROJECT_NAME
            Value: !Ref ProjectName
      Source:
        Type: GITHUB
        Location: !Ref GitHubRepository
        BuildSpec: buildspec.yml
        GitCloneDepth: 1
        ReportBuildStatus: true
      TimeoutInMinutes: !Ref BuildTimeout
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: !Ref CloudWatchLogGroup
          StreamName: build-logs
      Triggers:
        Webhook: !Ref EnableWebhook
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED
            - Type: BASE_REF
              Pattern: !Sub '^refs/heads/${GitHubBranch}$'

  # Scheduled Build (Nightly)
  ScheduledBuildRule:
    Type: AWS::Events::Rule
    Condition: !Equals [!Ref EnableScheduledBuilds, 'true']
    Properties:
      Name: !Sub '${ProjectName}-nightly-build'
      Description: Nightly build trigger
      ScheduleExpression: !Ref ScheduleExpression
      State: ENABLED
      Targets:
        - Id: CodeBuildTarget
          Arn: !Sub 'arn:aws:codebuild:${Region}:${AWS::AccountId}:project/${ProjectName}'
          RoleArn: !GetAtt CodeBuildRole.Arn

  # EventBridge Permission for CodeBuild
  EventBridgePermission:
    Type: AWS::Lambda::Permission
    Condition: !Equals [!Ref EnableScheduledBuilds, 'true']
    Properties:
      FunctionName: !Ref CodeBuildProject
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduledBuildRule.Arn

Outputs:
  CodeBuildProjectName:
    Description: CodeBuild Project Name
    Value: !Ref CodeBuildProject
    Export:
      Name: !Sub '${ProjectName}-CodeBuildProjectName'

  CodeBuildProjectArn:
    Description: CodeBuild Project ARN
    Value: !GetAtt CodeBuildProject.Arn
    Export:
      Name: !Sub '${ProjectName}-CodeBuildProjectArn'

  ECRRepositoryURI:
    Description: ECR Repository URI
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${Region}.amazonaws.com/${RepositoryName}'
    Export:
      Name: !Sub '${ProjectName}-ECRRepositoryURI'

  ECRRepositoryArn:
    Description: ECR Repository ARN
    Value: !GetAtt ECRRepository.Arn
    Export:
      Name: !Sub '${ProjectName}-ECRRepositoryArn'

  ArtifactBucketName:
    Description: S3 Artifact Bucket Name
    Value: !Ref ArtifactBucket
    Export:
      Name: !Sub '${ProjectName}-ArtifactBucketName'

  CloudWatchLogGroup:
    Description: CloudWatch Log Group
    Value: !Ref CloudWatchLogGroup
    Export:
      Name: !Sub '${ProjectName}-CloudWatchLogGroup'

  IAMRoleArn:
    Description: IAM Role ARN
    Value: !GetAtt CodeBuildRole.Arn
    Export:
      Name: !Sub '${ProjectName}-IAMRoleArn'

  ConsoleURL:
    Description: AWS Console URL for CodeBuild Project
    Value: !Sub 'https://${Region}.console.aws.amazon.com/codesuite/codebuild/projects/${ProjectName}'
