apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

# Update cluster name, region, and eks version if needed
metadata:
  name: eks-p4de-odcr
  region: PLACEHOLDER_AWS_REGION
  version: "1.32"

# List availability zones where cluster subnets will be created
availabilityZones:
  - PLACEHOLDER_AZ_1
  - PLACEHOLDER_AZ_2

iam:
  withOIDC: true

# EKS-managed node group(s)
managedNodeGroups:
  # Nodegroup for system pods
  - name: sys
    instanceType: c5.2xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true

  # GPU nodegroup
  # Update capacityReservationID below
  # Specify the availability zone matching the capacity reservation
  - name: p4de-odcr
    instanceType: p4de.24xlarge
    instancePrefix: p4de-odcr
    privateNetworking: true
    efaEnabled: true
    minSize: 0
    desiredCapacity: 2
    maxSize: 10
    availabilityZones: ["PLACEHOLDER_AZ_2"]
    capacityReservation:
      capacityReservationTarget:
        capacityReservationID: "PLACEHOLDER_CAPACITY_RESERVATION_ID"
    # Utilize the local instance store volume(s)
    overrideBootstrapCommand: |
      apiVersion: node.eks.aws/v1alpha1
      kind: NodeConfig
      spec:
        instance:
          localStorage:
            strategy: RAID0
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        fsx: true
