apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-p4de-odcr-vpc
  region: PLACEHOLDER_AWS_REGION
  version: "1.32"

# Substitute VPC and subnet IDs below
vpc:
  id: PLACEHOLDER_VPC_ID
  subnets:
    public:
      public-one:
        id: PLACEHOLDER_SUBNET_PUBLIC_1
      public-two:
        id: PLACEHOLDER_SUBNET_PUBLIC_2
    private:
      private-one:
        id: PLACEHOLDER_SUBNET_PRIVATE_1
      private-two:
        id: PLACEHOLDER_SUBNET_PRIVATE_2

iam:
  withOIDC: true

# EKS-managed node group(s)
managedNodeGroups:
  # Nodegroup for system pods
  - name: sys
    instanceType: c5.2xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true

  # GPU nodegroup
  # Update capacityReservationID below
  # Specify the subnet id matching the capacity reservation
  - name: p4de-odcr-vpc
    instanceType: p4de.24xlarge
    instancePrefix: p4de-odcr-vpc
    privateNetworking: true
    efaEnabled: true
    minSize: 0
    desiredCapacity: 2
    maxSize: 10
    subnets:
      - PLACEHOLDER_SUBNET_PRIVATE_2
    capacityReservation:
      capacityReservationTarget:
        capacityReservationID: "PLACEHOLDER_CAPACITY_RESERVATION_ID"
    # Utilize the local instance store volume(s)
    overrideBootstrapCommand: |
      apiVersion: node.eks.aws/v1alpha1
      kind: NodeConfig
      spec:
        instance:
          localStorage:
            strategy: RAID0
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        fsx: true
