apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-g4dn
  region: PLACEHOLDER_AWS_REGION
  version: "1.32"

# List availability zones where cluster subnets will be created
availabilityZones:
  - PLACEHOLDER_AZ_1
  - PLACEHOLDER_AZ_2

iam:
  withOIDC: true

# EKS-managed node group(s)
managedNodeGroups:
  # Nodegroup for system pods
  - name: sys
    instanceType: c5.2xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true

  # GPU nodegroup
  # List availability zones where instances in from this nodegroup will be launched
  - name: g4dn
    instanceType: g4dn.8xlarge
    instancePrefix: g4dn
    privateNetworking: true
    efaEnabled: true
    minSize: 0
    desiredCapacity: 2
    maxSize: 10
    availabilityZones: ["PLACEHOLDER_AZ_2"]
    # Utilize the local instance store volume(s)
    overrideBootstrapCommand: |
      apiVersion: node.eks.aws/v1alpha1
      kind: NodeConfig
      spec:
        instance:
          localStorage:
            strategy: RAID0
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        ebs: true
        fsx: true
