dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: AmazonLinux2
    image: amazonlinux:2
    groups:
      - amzn2
    pre_build_image: true
  # - name: CentOS7
  #   image: centos:7
  #   privileged: true
  #   pre_build_image: true
  # - name: Ubuntu2004
  #   image: ubuntu:20.04
  #   groups:
  #     - ubuntu
  #   privileged: true
  #   pre_build_image: true
  # - name: Ubuntu1804
  #   image: ubuntu:18.04
  #   groups:
  #     - ubuntu
  #   privileged: true
  #   pre_build_image: true
  # - name: Ubuntu1604
  #   image: ubuntu:16.04
  #   groups:
  #     - ubuntu
  #   privileged: true
  #   pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
