model:
  conv_layer_count: 5
  conv_layer_kernel: 3
  conv_layer_filters: 32

  layout: "NDHWC"
  script: False
  cuda_graph: True

  training:
    target_score: 0.124
    dropout_rate: 0.5
    weight_decay: 0

    momentum: 0.9
    amp: True

    optimizer: "fixed_sgd"

    lr_sched:
      lr: 0.004
      init_lr: 0.001
      warmup_epochs: 1

      decay_steps: [3, 4, 5]
      decay_values: [0.25, 0.125, 0.0625]

    train_epochs: 16

data:
  batch_size: 1
  dataset: "cosmoflow_tfr"

  apply_log: True
  shuffle: True
  preshuffle: True
  shard_type: "local"
  shard_multiplier: 1

  root_dir: "/dataset"
  stage: "/staging_area"
  stage_mode: "thread"
  stage_workers: 32

  sample_shape: [128, 128, 128, 4]
  target_shape: [4]

  dali_threads: 4
  data_layout: "NDHWC"

profile: False

