name: eks-cluster-manager
version: 1.0.0
description: |
  Discover, validate, and manage EKS clusters for training workloads.
  Supports interactive cluster selection, validation of required components
  (GPU plugin, EFA, Kubeflow), auto-fix of issues, and cluster creation.

triggers:
  - type: command
    pattern: "/manage-eks-cluster"
    description: "Manage EKS cluster for training"

parameters:
  - name: cluster_name
    type: string
    default: ""
    description: "Cluster name (auto-discover if empty)"
  
  - name: region
    type: string
    default: "us-west-2"
    description: "AWS region"
  
  - name: validate_components
    type: boolean
    default: true
    description: "Validate cluster components"
  
  - name: auto_fix
    type: boolean
    default: false
    description: "Auto-fix detected issues"
  
  - name: create_if_missing
    type: boolean
    default: false
    description: "Create cluster if none exist"
  
  - name: infrastructure_type
    type: string
    default: "cloudformation"
    description: "Infrastructure type: cloudformation or terraform"

outputs:
  - name: cluster_name
    type: string
    description: "Selected cluster name"
  
  - name: cluster_status
    type: string
    description: "Cluster status (PASS/WARNING/FAIL)"
  
  - name: validation_report
    type: object
    description: "Detailed validation results"
  
  - name: fixes_applied
    type: array
    description: "List of fixes applied"

dependencies:
  - aws-cli
  - kubectl
  - python3

examples:
  - command: "/manage-eks-cluster"
    description: "Discover and select cluster interactively"
  
  - command: "/manage-eks-cluster --cluster-name my-cluster --validate_components"
    description: "Validate specific cluster"
  
  - command: "/manage-eks-cluster --auto_fix --create_if_missing"
    description: "Auto-fix issues and create if needed"

author: opencode
license: MIT
