name: "Feature Request"
description: Suggest a new feature or enhancement.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: >
        Thank you for suggesting a feature! For major changes that affect the project's
        architecture or direction, please consider using the
        [RFC template](https://github.com/awslabs/awsome-distributed-training/issues/new?template=600-RFC.yml) instead.
  - type: textarea
    id: description
    attributes:
      label: Feature Description & Motivation
      description: Describe the feature you'd like and why it would be useful.
      placeholder: |
        What problem does this feature solve? Who would benefit from it?
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category best describes this feature request?
      options:
        - New architecture reference
        - New test case
        - Enhancement to existing test case
        - AMI / container image
        - Validation / observability tooling
        - Micro-benchmark
        - Documentation
        - CI/CD improvement
        - Other
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternatives you've considered.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request.
    validations:
      required: false
