AWSTemplateFormatVersion: '2010-09-09'
Description: VPC Stack

Parameters:
  ResourceNamePrefix:
    Description: Prefix to be used for all resources created by this template.
    Type: String
    Default: sagemaker-hyperpod-eks

  VpcCIDR:
    Description: The IP range (CIDR notation) for the VPC.
    Type: String
    Default: 10.192.0.0/16

  PublicSubnet1CIDR:
    Description: The IP range (CIDR notation) for the public subnet in the first Availability Zone.
    Type: String
    Default: 10.192.10.0/24

  PublicSubnet2CIDR:
    Description: The IP range (CIDR notation) for the public subnet in the second Availability Zone. 
    Type: String
    Default: 10.192.11.0/24
  
  IsLocalZone:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false'] 
    Description: Set to true if using Local Zone Deployment (for GB200)
  
  NATGatewayAZ:
    Type: String
    Default: 'use1-az2'
    Description: Standard AZ for NAT Gateway when using Local Zone Deployment (for GB200)

Conditions:
  UseLocalZoneNATGateway: !Equals [!Ref IsLocalZone, 'true']
  UseStandardNATGateway: !Equals [!Ref IsLocalZone, 'false']

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub '${ResourceNamePrefix}-SMHP-VPC'

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ResourceNamePrefix}-SMHP-IGW
  
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${ResourceNamePrefix}-SMHP-Public1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${ResourceNamePrefix}-SMHP-Public2

  # Standard NAT Gateway

  NatGateway1EIP:
    Type: AWS::EC2::EIP
    Condition: UseStandardNATGateway
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc

  NatGateway2EIP:
    Type: AWS::EC2::EIP
    Condition: UseStandardNATGateway
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc

  NatGateway1:
    Type: AWS::EC2::NatGateway
    Condition: UseStandardNATGateway
    Properties:
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId: !Ref PublicSubnet1

  NatGateway2:
    Type: AWS::EC2::NatGateway
    Condition: UseStandardNATGateway
    Properties:
      AllocationId: !GetAtt NatGateway2EIP.AllocationId
      SubnetId: !Ref PublicSubnet2
  
  # Local Zone NAT Gateway

  LocalZoneNATGatewaySubnet:
    Condition: UseLocalZoneNATGateway
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.192.128.0/24
      AvailabilityZone: !Ref NATGatewayAZ
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${ResourceNamePrefix}-SMHP-Public-NAT-GW-Subnet
  
  LocalZoneNATGatewaySubnetAssociation:
    Condition: UseLocalZoneNATGateway
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref LocalZoneNATGatewaySubnet
  
  LocalZoneNATGatewayEIP:
    Condition: UseLocalZoneNATGateway
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  
  LocalZoneNATGateway:
    Condition: UseLocalZoneNATGateway
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt LocalZoneNATGatewayEIP.AllocationId
      SubnetId: !Ref LocalZoneNATGatewaySubnet
  
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ResourceNamePrefix}-SMHP-Public-Routes

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2

Outputs:
  NatGatewayId: 
    Description: Nat Gateway Id
    Value: !If
      - UseStandardNATGateway
      - !Ref NatGateway1
      - !Ref LocalZoneNATGateway

  VpcId:
    Description: VPC Id
    Value: !Ref VPC
