---
- name: Python docker client for ansible docker plugin.
  ansible.builtin.pip:
    executable: pip3
    name:
      - docker==6.1.3

- name: "GPU monitoring - dcgm"
  docker_container:
    name: dcgm-exporter
    image: nvcr.io/nvidia/k8s/dcgm-exporter:{{ dcgm_container_tag }}
    detach: yes
    restart_policy: unless-stopped
    network_mode: host
    runtime: nvidia
    capabilities:
      - SYS_ADMIN
    env:
      NVIDIA_VISIBLE_DEVICES: all
      DCGM_EXPORTER_LISTEN: ":9400"
