---
- name: "Install lustre client"
  ansible.builtin.shell:
    cmd: "PYTHON=python2 amazon-linux-extras install -y {{ aws_lustre_package }}"
    creates: "/sbin/mount.lustre"

- name: "Create lustre mountpoints"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
  loop: "{{ aws_lustre_mounts }}"

- name: "Define/mount lustre filesystems"
  ansible.builtin.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    opts: "{{ item.opts|default(defaults,noatime,flock,_netdev) }}"
    state: "{{ item.state|default(mounted) }}"
  loop: "{{ aws_lustre_mounts }}"
