---
- name: Creates directory
  file:
    path: /etc/enroot/
    state: directory

- name: Copy enroot conf
  ansible.builtin.template:
    src: enroot.conf
    dest: /etc/enroot/enroot.conf
    mode: '0644'

- name: "Clone Pyxis"
  ansible.builtin.git:
    repo: 'https://github.com/NVIDIA/pyxis.git'
    dest: /tmp/pyxis
    version: "{{ pyxis_version }}"
    depth: 1

- name: "Get dependencies for Enroot and Pyxis"
  ansible.builtin.shell: |
    sudo yum install -y jq squashfs-tools parallel libnvidia-container-tools pigz squashfuse slurm-devel
    export arch=$(uname -m) && sudo -E yum install -y https://github.com/NVIDIA/enroot/releases/download/v3.4.0/enroot-3.4.0-2.el7.${arch}.rpm
    export arch=$(uname -m) && sudo -E yum install -y https://github.com/NVIDIA/enroot/releases/download/v3.4.0/enroot+caps-3.4.0-2.el7.${arch}.rpm
    # get overlayfs
    wget http://mirror.centos.org/centos/7/extras/x86_64/Packages/fuse-overlayfs-0.7.2-6.el7_8.x86_64.rpm
    sudo yum localinstall -y fuse-overlayfs-0.7.2-6.el7_8.x86_64.rpm
    rm fuse-overlayfs-0.7.2-6.el7_8.x86_64.rpm

- name: "Install Enroot and Pyxis"
  ansible.builtin.shell: |
    cd /tmp/pyxis
    sudo CPPFLAGS='-I /opt/slurm/include/' make
    sudo CPPFLAGS='-I /opt/slurm/include/' make install
    sudo mv /tmp/enroot.conf /etc/enroot/enroot.conf
    sudo mkdir -p /opt/slurm/etc/plugstack.conf.d
    echo -e 'include /opt/slurm/etc/plugstack.conf.d/*' | sudo tee /opt/slurm/etc/plugstack.conf
    sudo ln -fs /usr/local/share/pyxis/pyxis.conf /opt/slurm/etc/plugstack.conf.d/pyxis.conf

- name: yum clean metadata
  ansible.builtin.command:
    cmd: yum clean metadata
