---
- name: "Download AWS CLI v2"
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscli-exe-linux-x86_64.zip
    mode: '0755'

- name: Install packages required unzip, sudo
  ansible.builtin.package:
    name:
      - unzip
      - sudo
    state: present

- name: "Extract AWS CLI v2"
  ansible.builtin.unarchive:
    src: /tmp/awscli-exe-linux-x86_64.zip
    dest: /tmp
    remote_src: yes

- name: "Install AWS CLI v2"
  ansible.builtin.command: /tmp/aws/install
  become: yes

- name: "Configure S3 parameters for AWS CLI v2"
  ansible.builtin.command: aws configure set default.s3.max_concurrent_requests 1
    # aws configure set default.s3.max_queue_size 10000
    # aws configure set default.s3.multipart_threshold 64MB
    # aws configure set default.s3.multipart_chunksize 16MB
