apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fsx-sc
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: ${FSX_FILESYSTEM_ID}  # Replace with your FSx filesystem ID
    volumeAttributes:
      dnsname: ${FSX_DNS_NAME}  # Replace with your FSx DNS name
      mountname: ${FSX_MOUNT_NAME}  # Replace with your FSx mount name 