apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <my-p4de-eks-cluster>
  version: "1.27"
  region: us-west-2
  tags:
    karpenter.sh/discovery: awsankur-p4de-cluster

availabilityZones:
  - us-west-2a
  - us-west-2b
  - us-west-2c
  - us-west-2d

managedNodeGroups:

  - name: sys
    instanceType: c5.2xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true

  - name: p4de-nodes
    instanceType: p4de.24xlarge
    instancePrefix: p4de-odcr-nodes
    privateNetworking: true
    availabilityZones: ["us-west-2b"]
    efaEnabled: true
    minSize: 2
    desiredCapacity: 2
    maxSize: 10
    volumeSize: 900
    capacityReservation:
      capacityReservationTarget:
        capacityReservationID: "cr-id"
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        fsx: true

iam:
  withOIDC: true