name: docker-image-builder
version: 1.0.0
description: |
  Intelligently builds Docker images with automatic conflict detection and resolution.
  Analyzes Dockerfiles and requirements.txt for compatibility issues, auto-fixes
  PyTorch/CUDA mismatches, and rebuilds on failure (max 3 attempts).

triggers:
  - type: command
    pattern: "/build-docker-image"
    description: "Build a Docker image with auto-fix capabilities"
  - type: file_change
    pattern: "Dockerfile"
    description: "Auto-trigger on Dockerfile changes"

parameters:
  - name: dockerfile
    type: string
    default: "Dockerfile"
    description: "Path to Dockerfile"
  
  - name: context
    type: string
    default: "."
    description: "Build context path"
  
  - name: tag
    type: string
    default: "auto"
    description: "Image tag (auto generates from git/commit)"
  
  - name: auto_fix
    type: boolean
    default: true
    description: "Automatically fix detected conflicts"
  
  - name: max_attempts
    type: integer
    default: 3
    description: "Maximum rebuild attempts on failure"
  
  - name: base_image
    type: string
    default: ""
    description: "Override base image (auto-detect if empty)"
  
  - name: verbose
    type: boolean
    default: true
    description: "Show detailed status updates"
  
  - name: use_sudo
    type: boolean
    default: false
    description: "Use sudo for Docker commands"

outputs:
  - name: image_name
    type: string
    description: "Name of the built image"
  
  - name: build_time
    type: string
    description: "Total build time"
  
  - name: attempts
    type: integer
    description: "Number of build attempts"
  
  - name: fixes_applied
    type: array
    description: "List of fixes applied"
  
  - name: success
    type: boolean
    description: "Whether build succeeded"

dependencies:
  - docker
  - python3
  - git

examples:
  - command: "/build-docker-image"
    description: "Build with auto-detected settings"
  
  - command: "/build-docker-image --dockerfile ./docker/Dockerfile.gpu"
    description: "Build from specific Dockerfile"
  
  - command: "/build-docker-image --tag myapp:v1.0 --auto_fix=false"
    description: "Build with specific tag, no auto-fix"

author: opencode
license: MIT
