## Head node
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 15s
        evaluation_interval: 15s
      scrape_configs:
        - job_name: 'node-exporter'
          static_configs:
            - targets: ['localhost:9100']
        - job_name: 'slurm_exporter'
          static_configs:
            - targets: ['localhost:8080']

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

exporters:
  prometheusremotewrite:
    endpoint: ${AMPREMOTEWRITEURL}
    auth:
      authenticator: sigv4auth

extensions:
  sigv4auth:
    region: ${REGION}
    service: aps

service:
  extensions: [sigv4auth]
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]
      
      
## Compute Node OTEL Config (with GPU)
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 15s
        evaluation_interval: 15s
      scrape_configs:
        - job_name: 'node_exporter'
          static_configs:
            - targets: ['localhost:9100']
        - job_name: 'dcgm_exporter'
          static_configs:
            - targets: ['localhost:9400']
        - job_name: 'efa_exporter'
          static_configs:
            - targets: ['localhost:9109']
            
processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

exporters:
  prometheusremotewrite:
    endpoint: ${AMPREMOTEWRITEURL}
    auth:
      authenticator: sigv4auth

extensions:
  sigv4auth:
    region: ${REGION}
    service: aps

service:
  extensions: [sigv4auth]
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite] 
