apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-g4dn-vpc
  region: PLACEHOLDER_AWS_REGION
  version: "1.32"

iam:
  withOIDC: true

# Substitute VPC and subnet IDs below
vpc:
  id: PLACEHOLDER_VPC_ID
  subnets:
    public:
      public-one:
        id: PLACEHOLDER_SUBNET_PUBLIC_1
      public-two:
        id: PLACEHOLDER_SUBNET_PUBLIC_2
    private:
      private-one:
        id: PLACEHOLDER_SUBNET_PRIVATE_1
      private-two:
        id: PLACEHOLDER_SUBNET_PRIVATE_2

# EKS-managed node group(s)
managedNodeGroups:
  # Nodegroup for system pods
  - name: sys
    instanceType: c5.2xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true

  # GPU nodegroup
  # Update capacityReservationID below
  # specify the subnet id corresponding to the capacity reservation
  - name: g4dn
    instanceType: g4dn.8xlarge
    instancePrefix: g4dn-vpc
    privateNetworking: true
    efaEnabled: true
    minSize: 0
    desiredCapacity: 2
    maxSize: 10
    subnets:
      - PLACEHOLDER_SUBNET_PRIVATE_2
    # Utilize the local instance store volume(s)
    overrideBootstrapCommand: |
      apiVersion: node.eks.aws/v1alpha1
      kind: NodeConfig
      spec:
        instance:
          localStorage:
            strategy: RAID0
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        ebs: true
        fsx: true
