apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-p5-odcr-vpc
  region: PLACEHOLDER_AWS_REGION
  version: "1.32"

# Substitute VPC and subnet IDs below
vpc:
  id: PLACEHOLDER_VPC_ID
  subnets:
    private:
      private-one:
        id: PLACEHOLDER_SUBNET_PRIVATE_1
      private-two:
        id: PLACEHOLDER_SUBNET_PRIVATE_2
    public:
      public-one:
        id: PLACEHOLDER_SUBNET_PUBLIC_1
      public-two:
        id: PLACEHOLDER_SUBNET_PUBLIC_2

iam:
  withOIDC: true

# EKS-managed node group(s)
managedNodeGroups:
  # Update capacityReservationID below
  - name: p5-ocdr
    instanceType: p5.48xlarge
    instancePrefix: p5-odcr-nodes
    privateNetworking: true
    efaEnabled: true
    minSize: 0
    desiredCapacity: 1
    maxSize: 10
    capacityReservation:
      capacityReservationTarget:
        capacityReservationID: "cr-xxxxxxxxxx"
    # Utilize the local instance store volume(s)
    overrideBootstrapCommand: |
      apiVersion: node.eks.aws/v1alpha1
      kind: NodeConfig
      spec:
        instance:
          localStorage:
            strategy: RAID0
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        fsx: true
