# GPT-2 pretraining setup
{

   "tokenizer_type": "HFTokenizer",
   "data-path": "/fsx/data/olcf/all_text_document",
   "vocab-file": "/fsx/data/olcf/all_vocab.json",

   # parallelism settings ( you will want to change these based on your cluster setup, ideally scheduling pipeline stages
   # across the node boundaries )
   #"pipe-parallel-size": 1,
   "model-parallel-size": 2,

   # batch / data settings
   "train_micro_batch_size_per_gpu": 12,
   "gradient_accumulation_steps": 2,
   "data-impl": "mmap",

   #aws-rccl workaround
   "num_workers": 0,

   # model settings
   "num-layers": 40,
   "hidden-size": 5120,
   "num-attention-heads": 40,
   "seq-length": 2048,
   "max-position-embeddings": 2048,
   "norm": "layernorm",
   "pos-emb": "rotary",
   "no-weight-tying": true,
   "gpt_j_residual": false,
   "output_layer_parallelism": "column",

   # these should provide some speedup but takes a while to build, set to true if desired
   "scaled-upper-triang-masked-softmax-fusion": true,
   "bias-gelu-fusion": true,

   # init methods
   "init_method": "small_init",
   "output_layer_init_method": "wang_init",


   # optimizer settings
   "optimizer": {
     "type": "adam",
     "params": {
       "lr": 0.006,
       "betas": [0.9, 0.999],
       "eps": 1.0e-8,
     }
   },
   "min_lr": 0.00006,

   # for all zero_optimization options, see https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
  },


   # activation checkpointing
   "checkpoint-activations": true,
   "checkpoint-num-layers": 1,
   "partition-activations": true,
   "synchronize-each-layer": true,

   # regularization
   "gradient_clipping": 1.0,
   "weight-decay": 0.1,
   "hidden-dropout": 0,
   "attention-dropout": 0,

   # precision settings
   "fp16": {
     "type": "bfloat16",
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "hysteresis": 2,
     "min_loss_scale": 1
   },

   # misc. training settings
   "train-iters": 15300,
   "lr-decay-iters": 15300,
   "distributed-backend": "nccl",
   "lr-decay-style": "cosine",
   "warmup": 0.01,
   "checkpoint-factor": 50,
   "eval-interval": 100,
   "eval-iters": 10,

   # logging
   "log-interval": 50,
   "steps_per_print": 10,
   "keep-last-n-checkpoints": 200,
   "wall_clock_breakdown": true,
}
