ENV EFA_INSTALLER_VERSION=1.37.0
ENV AWS_OFI_NCCL_VERSION=v1.13.2-aws
ENV NCCL_VERSION=v2.23.4-1
ENV NCCL_TESTS_VERSION=v2.13.10
FROM public.ecr.aws/hpc-cloud/nccl-tests:efa${EFA_INSTALLER_VERSION}-ofi${AWS_OFI_NCCL_VERSION}-nccl${NCCL_VERSION}-tests${NCCL_TESTS_VERSION}
